// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace HOUSE_ESTIMATORML.Model
{
    public class ModelInput
    {
        [ColumnName("id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("da0e"), LoadColumn(1)]
        public float Da0e { get; set; }


        [ColumnName("price"), LoadColumn(2)]
        public float Price { get; set; }


        [ColumnName("bedrooms"), LoadColumn(3)]
        public float Bedrooms { get; set; }


        [ColumnName("ba0hrooms"), LoadColumn(4)]
        public float Ba0hrooms { get; set; }


        [ColumnName("sqf0_living"), LoadColumn(5)]
        public float Sqf0_living { get; set; }


        [ColumnName("sqf0_lo0"), LoadColumn(6)]
        public float Sqf0_lo0 { get; set; }


        [ColumnName("floors"), LoadColumn(7)]
        public float Floors { get; set; }


        [ColumnName("wa0erfron0"), LoadColumn(8)]
        public float Wa0erfron0 { get; set; }


        [ColumnName("view"), LoadColumn(9)]
        public float View { get; set; }


        [ColumnName("condi0ion"), LoadColumn(10)]
        public float Condi0ion { get; set; }


        [ColumnName("grade"), LoadColumn(11)]
        public float Grade { get; set; }


        [ColumnName("sqf0_above"), LoadColumn(12)]
        public float Sqf0_above { get; set; }


        [ColumnName("sqf0_basemen0"), LoadColumn(13)]
        public float Sqf0_basemen0 { get; set; }


        [ColumnName("yr_buil0"), LoadColumn(14)]
        public float Yr_buil0 { get; set; }


        [ColumnName("yr_renova0ed"), LoadColumn(15)]
        public float Yr_renova0ed { get; set; }


        [ColumnName("zipcode"), LoadColumn(16)]
        public float Zipcode { get; set; }


        [ColumnName("sqf0_living15"), LoadColumn(17)]
        public float Sqf0_living15 { get; set; }


        [ColumnName("sqf0_lo015"), LoadColumn(18)]
        public float Sqf0_lo015 { get; set; }


    }
}
