// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dbtest;

namespace API.Data.Migrations
{
    [DbContext(typeof(HouseDatabase))]
    [Migration("20201116163418_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("dbtest.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Bathrooms")
                        .HasColumnType("REAL");

                    b.Property<double>("Bedrooms")
                        .HasColumnType("REAL");

                    b.Property<double>("Condition")
                        .HasColumnType("REAL");

                    b.Property<double>("Date")
                        .HasColumnType("REAL");

                    b.Property<double>("Floors")
                        .HasColumnType("REAL");

                    b.Property<double>("Grade")
                        .HasColumnType("REAL");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Longg")
                        .HasColumnType("REAL");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("Sqft_above")
                        .HasColumnType("REAL");

                    b.Property<double>("Sqft_basement")
                        .HasColumnType("REAL");

                    b.Property<double>("Sqft_living")
                        .HasColumnType("REAL");

                    b.Property<double>("Sqft_living15")
                        .HasColumnType("REAL");

                    b.Property<double>("Sqft_lot")
                        .HasColumnType("REAL");

                    b.Property<double>("Sqft_lot15")
                        .HasColumnType("REAL");

                    b.Property<double>("View")
                        .HasColumnType("REAL");

                    b.Property<double>("Waterfront")
                        .HasColumnType("REAL");

                    b.Property<double>("Yr_built")
                        .HasColumnType("REAL");

                    b.Property<double>("Yr_renovated")
                        .HasColumnType("REAL");

                    b.Property<double>("Zipcode")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
